version: "3"
services:
  rpi-lib-builder:
    build: .
    user: "root"
    working_dir: /code
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./build:/home
    command: ./${BUILD_SCRIPT}
